apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: argocd
type: Opaque
data:
  # Format: username:password (base64 encoded)
  # Eg: echo -n "username:password" | base64
  # Token permissions: read:packages
  creds: U2F1bE1hcmNpYWw6Z2hwX0NzdHlld2ZHb09lRlpib2gyUUdmYzdqR0N4akgxMDNhcE9zNA==